title: "Learn You a Haskell for Great Good! 日本語版"
description: "最高におもしろいHaskellを学ぼう!"
url: https://moutend.github.io/jlyhgg/

encoding: UTF-8
permalink: pretty
markdown:    kramdown

sass:
  sass_dir:  _scss
  style:    :compressed

exclude:
  - "README.md"
  - "Gemfile"
  - "vendor"
